/*
 * Copyright © 2019 Tinkoff Bank
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ru.tinkoff.vkarmane.sdk.constants


enum class CountryCode(val code: Int, val isoCode: String) {
    AFGHANISTAN(0, "AF"),
    ALBANIA(1, "AL"),
    ALGERIA(2, "DZ"),
    ANDORRA(3, "AD"),
    ANGOLA(4, "AO"),
    ANTIGUA_AND_BARBUDA(5, "AG"),
    ARGENTINA(6, "AR"),
    ARMENIA(7, "AM"),
    AUSTRALIA(8, "AU"),
    AUSTRIA(9, "AT"),
    AZERBAIJAN(10, "AZ"),
    BAHAMAS(11, "BS"),
    BAHRAIN(12, "BH"),
    BANGLADESH(13, "BD"),
    BARBADOS(14, "BB"),
    BELARUS(15, "BY"),
    BELGIUM(16, "BE"),
    BELIZE(17, "BZ"),
    BENIN(18, "BJ"),
    BHUTAN(19, "BT"),
    BOLIVIA(20, "BO"),
    BOSNIA(21, "BA"),
    BOTSWANA(22, "BW"),
    BRAZIL(23, "BR"),
    BRUNEI(24, "BN"),
    BULGARIA(25, "BG"),
    BURKINA_FASO(26, "BF"),
    MYANMAR(27, "MM"),
    BURUNDI(28, "BI"),
    CAMBODIA(29, "KH"),
    CAMEROON(30, "CM"),
    CANADA(31, "CA"),
    CABO_VERDE(32, "CV"),
    CENTRAL_AFRICAN_REPUBLIC(33, "CF"),
    CHAD(34, "TD"),
    CHILE(35, "CL"),
    CHINA(36, "CN"),
    COLOMBIA(37, "CO"),
    COMOROS(38, "KM"),
    CONGO(39, "CD"),
    COSTA_RICA(40, "CR"),
    COTE_D_IVOIRE(41, "CI"),
    CROATIA(42, "HR"),
    CUBA(43, "CU"),
    CYPRUS(44, "CY"),
    CZECHIA(45, "CZ"),
    DENMARK(46, "DK"),
    DJIBOUTI(47, "DJ"),
    DOMINICA(48, "DM"),
    DOMINICAN_REPUBLIC(49, "DO"),
    TIMOR_LESTE(50, "TL"),
    ECUADOR(51, "EC"),
    EGYPT(52, "EG"),
    SALVADOR(53, "SV"),
    EQUATORIAL_GUINEA(54, "GQ"),
    ERITREA(55, "ER"),
    ESTONIA(56, "EE"),
    ETHIOPIA(57, "ET"),
    FIJI(58, "FJ"),
    FINLAND(59, "FI"),
    FRANCE(60, "FR"),
    GABON(61, "GA"),
    GAMBIA(62, "GM"),
    GEORGIA(63, "GE"),
    GERMANY(64, "DE"),
    GHANA(65, "GH"),
    GREECE(66, "GR"),
    GRENADA(67, "GD"),
    GUATEMALA(68, "GT"),
    GUINEA(69, "GN"),
    GUINEA_BISSAU(70, "GW"),
    HAITI(71, "HT"),
    HONDURAS(72, "HN"),
    HONG_KONG(73, "HK"),
    HUNGARY(74, "HU"),
    ICELAND(75, "IS"),
    INDIA(76, "IN"),
    INDONESIA(77, "ID"),
    IRAN(78, "IR"),
    IRAQ(79, "IQ"),
    IRELAND(80, "IE"),
    ISRAEL(81, "IL"),
    ITALY(82, "IT"),
    JAMAICA(83, "JM"),
    JAPAN(84, "JP"),
    JORDAN(85, "JO"),
    KAZAKHSTAN(86, "KZ"),
    KENYA(87, "KE"),
    KIRIBATI(88, "KI"),
    NORTH_KOREA(89, "KP"),
    SOUTH_KOREA(90, "KR"),
    KOSOVO(91, "XK"),
    KUWAIT(92, "KW"),
    KYRGYZSTAN(93, "KG"),
    LAOS(94, "LA"),
    LATVIA(95, "LV"),
    LEBANON(96, "LB"),
    LESOTHO(97, "LS"),
    LIBERIA(98, "LR"),
    LIBYA(99, "LY"),
    LIECHTENSTEIN(100, "LI"),
    LITHUANIA(101, "LT"),
    LUXEMBOURG(102, "LU"),
    MACEDONIA(103, "MK"),
    MADAGASCAR(104, "MG"),
    MALAWI(105, "MW"),
    MALAYSIA(106, "MY"),
    MALDIVES(107, "MV"),
    MALI(108, "ML"),
    MALTA(109, "MT"),
    MARSHALL_ISLANDS(110, "MH"),
    MARTINIQUE(111, "MQ"),
    MAURITIUS(112, "MU"),
    MEXICO(113, "MX"),
    MICRONESIA(114, "FM"),
    MOLDOVA(115, "MD"),
    MONACO(116, "MC"),
    MONGOLIA(117, "MN"),
    MONTENEGRO(118, "ME"),
    MOROCCO(119, "MA"),
    MOZAMBIQUE(120, "MZ"),
    NAMIBIA(121, "NA"),
    NAURU(122, "NR"),
    NEPAL(123, "NP"),
    NETHERLANDS(124, "NL"),
    NEW_ZEALAND(125, "NZ"),
    NICARAGUA(126, "NI"),
    NIGER(127, "NE"),
    NIGERIA(128, "NG"),
    NORWAY(129, "NO"),
    OMAN(130, "OM"),
    PAKISTAN(131, "PK"),
    PALAU(132, "PW"),
    PALESTINE(133, "PS"),
    PANAMA(134, "PA"),
    NEW_GUINEA(135, "PG"),
    PARAGUAY(136, "PY"),
    PERU(137, "PE"),
    PHILIPPINES(138, "PH"),
    POLAND(139, "PL"),
    PORTUGAL(140, "PT"),
    QATAR(141, "QA"),
    ROMANIA(142, "RO"),
    RUSSIA(143, "RU"),
    RWANDA(144, "RW"),
    SAINT_KITTS(145, "KN"),
    SAINT_LUCIA(146, "LC"),
    SAINT_VINCENT(147, "VC"),
    SAMOA(148, "WS"),
    SAN_MARINO(149, "SM"),
    SAO_TOME(150, "ST"),
    SAUDI_ARABIA(151, "SA"),
    SENEGAL(152, "SN"),
    SERBIA(153, "RS"),
    SEYCHELLES(154, "SC"),
    SIERRA_LEONE(155, "SL"),
    SINGAPORE(156, "SG"),
    SINT_MAARTEN(157, "SX"),
    SLOVAKIA(158, "SK"),
    SLOVENIA(159, "SI"),
    SOLOMON_ISLANDS(160, "SB"),
    SOMALIA(161, "SO"),
    SOUTH_AFRICA(162, "ZA"),
    SOUTH_SUDAN(163, "SS"),
    SPAIN(164, "ES"),
    SRI_LANKA(165, "LK"),
    SUDAN(166, "SD"),
    SURINAME(167, "SR"),
    SWEDEN(168, "SE"),
    SWITZERLAND(169, "CH"),
    SYRIAN(170, "SY"),
    TAJIKISTAN(171, "TJ"),
    TANZANIA(172, "TZ"),
    THAILAND(173, "TH"),
    TOGO(174, "TG"),
    TONGA(175, "TO"),
    TRINIDAD_AND_TOBAGO(176, "TT"),
    TUNISIA(177, "TN"),
    TURKEY(178, "TR"),
    TURKMENISTAN(179, "TM"),
    TUVALU(180, "TV"),
    UGANDA(181, "UG"),
    UKRAINE(182, "UA"),
    UNITED_ARAB_EMIRATES(183, "AE"),
    UK(184, "GB"),
    USA(185, "US"),
    URUGUAY(186, "UY"),
    UZBEKISTAN(187, "UZ"),
    VANUATU(188, "VU"),
    VATICAN(189, "VA"),
    VENEZUELA(190, "VE"),
    VIETNAM(191, "VN"),
    YEMEN(192, "YE"),
    ZAMBIA(193, "ZM"),
    ZIMBABWE(194, "ZW"),
    UNKNOWN(-1, "");

    companion object {
        @JvmStatic
        fun fromInt(value: Int): CountryCode {
            return values().firstOrNull { value == it.code } ?: UNKNOWN
        }
    }
}
